### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/webv3#3]

**Comment by Heartless49** [comment]
This will be VERY simple, since this site is being built with a much easier component style. The only thing that I'm going to need is the `Tracking Code` from the google account that you want to use for this.

Following this guide, we can literally track everything on the site and I can set it all up pretty easily.

https://medium.com/google-cloud/tracking-site-visits-on-react-app-hosted-in-google-cloud-using-google-analytics-f49c2411d398

I've got the analytics module installed on my local; once I get that code I can throw that in and everything should work perfectly.
